name: RandomSpotTeleport
main: com.github.owatakun.rstp.RandomSpotTeleport
version: 1.0.2
description: Teleport randomly from the set point
commands:
  rstp:
    description: Give the all the privileges of RandomSpotTeleport
    aliases: randomspotteleport
    usage: |
           /rstp tp <ListName> - テレポートを実行
           /rstp reload - 設定のリロード
           /rstp list <ListName> [pageNo] - リストを表示
           /rstp add <ListName> <pointName> <here or x y z> - 現在位置(指定位置)をリストに追加
           /rstp remove <ListName> <pointName> - 指定位置をリストから削除
           /rstp stp <ListName> <pointName> [playername] - 指定位置に(指定プレイヤーを)TP 省略時はsender
           /rstp save - 設定をすべて保存
    permission: Randomcolor
    permission-message: You don't have permission!
permissions:
  randomspotteleport.*:
    description: Give the all the privileges of RandomSpotTeleport
    default: op