name: RandomSpotTeleport
main: com.github.owatakun.rstp.RandomSpotTeleport
version: 1.1.0
description: Teleport randomly from the set point
commands:
  rstp:
    description: Give the all the privileges of RandomSpotTeleport
    aliases: randomspotteleport
    usage: |
           /rstp tp <ListName> - テレポートを実行
           /rstp reload - 設定のリロード
           /rstp list <ListName> [pageNo] - リストを表示
           /rstp add <ListName> [pointName] - 現在位置をリストに追加
           /rstp remove <ListName> <pointName> - 指定位置をリストから削除
           /rstp stp <ListName> <pointName> [playername] - 指定位置に(指定プレイヤーを)TP
           /rstp save - 設定をすべて保存
    permission: randomspotteleport.admin
    permission-message: You don't have permission!
permissions:
  randomspotteleport.*:
    description: Give the all the privileges of RandomSpotTeleport
    children:
      randomspotteleport.admin: true
  randomspotteleport.admin:
    description: Allow autokicker commands.
    default: op